version: "3.2"

services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.zsh_history:/root/.zsh_history:z
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=Asia/Bangkok
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
