
name: Build LaTeX document
on: 
  workflow_call:
    inputs:
      texfile:
        description: The main LaTeX file to compile
        type: string
        required: true
      bibfile:
        description: The main BibTeX file to compile
        type: string
        required: true
      output_dir:
        description: The directory to store the artifacts
        type: string
        required: true

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v2
    - name: List files
      run: ls -R
    - name: Install LaTeX's dependencies
      run: sudo apt-get update && sudo apt-get install texlive texlive-xetex texlive-publishers texlive-science latexmk cm-super 
    - name: First compliation
      continue-on-error: true
      run: xelatex ${{ env.TEXFILE }}; bibtex ${{ env.BIBFILE }};
      # run: latexmk -xelatex -bibtex ${{ env.TEXFILE }}
      # run: pdflatex ${{ env.TEXFILE }}; bibtex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }};
    - name: Second compliation
      continue-on-error: true
      run: xelatex ${{ env.TEXFILE }}; xelatex ${{ env.TEXFILE }};
      # run: latexmk -xelatex -bibtex ${{ env.TEXFILE }}
      # run: pdflatex ${{ env.TEXFILE }}; bibtex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }};
    - name: List files
      run: ls -R
    - name: Move pdf to artifacts
      run: mkdir -p ${{ env.OUTPUT_DIR }} && mv ${{ env.TEXFILE }}.pdf ${{ env.OUTPUT_DIR }}/${{ env.TEXFILE }}.pdf
    - name: List files
      run: ls -R
    - name: Upload pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.TEXFILE }}.pdf
        path: ./${{ env.OUTPUT_DIR }}
