env: 
  TEXFILE: codern-report
  BIBFILE: codern
  OUTPUT_DIR: github_artifacts
  DEPLOY_DIR: github_deploy
  DEPLOY_BRANCH: build

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v2
    - name: List files
      run: ls -R
    - name: Install LaTeX's dependencies
      run: sudo apt-get update && sudo apt-get install texlive texlive-xetex texlive-publishers texlive-science latexmk cm-super 
    - name: First compliation
      continue-on-error: true
      run: xelatex ${{ env.TEXFILE }}.tex; bibtex ${{ env.BIBFILE }};
      # run: latexmk -xelatex -bibtex ${{ env.TEXFILE }}
      # run: pdflatex ${{ env.TEXFILE }}; bibtex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }};
    - name: Second compliation
      continue-on-error: true
      run: xelatex ${{ env.TEXFILE }}.tex; xelatex ${{ env.TEXFILE }}.tex;
      # run: latexmk -xelatex -bibtex ${{ env.TEXFILE }}
      # run: pdflatex ${{ env.TEXFILE }}; bibtex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }}; pdflatex ${{ env.TEXFILE }};
    - name: List files
      run: ls -R
    - name: Move pdf to artifacts
      run: mkdir -p ${{ env.OUTPUT_DIR }} && mv ${{ env.TEXFILE }}.pdf ${{ env.OUTPUT_DIR }}/${{ env.TEXFILE }}.pdf
    - name: List files
      run: ls -R
    - name: Upload pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.TEXFILE }}.pdf
        path: ./${{ env.OUTPUT_DIR }}

  deploy:
    needs: [build_latex]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: Move files
        run: mkdir -p ${{ env.DEPLOY_DIR }} && mv ${{ env.OUTPUT_DIR }}/*/* ${{ env.DEPLOY_DIR  }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ${{ env.DEPLOY_DIR }}
          publish_branch: ${{ env.DEPLOY_BRANCH}}
          force_orphan: true # Force orphan