env: 
  FILE: codern-report
  OUTPUT_DIR: artifacts

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v2
    - name: Install LaTeX's dependencies
      run: sudo apt-get update && sudo apt-get install texlive texlive-xelatex texlive-publishers texlive-science latexmk cm-super 
    - name: Compile with XeLaTeX + BibTeX
      # run: xelatex ${{ env.FILE }}.tex; xelatex ${{ env.FILE }}.tex; bibtex ${{ env.FILE }}; xelatex ${{ env.FILE }}.tex; xelatex ${{ env.FILE }}.tex;
      run: latexmk -xelatex -bibtex ${{ env.FILE }}
      # run: pdflatex ${{ env.FILE }}; bibtex ${{ env.FILE }}; pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
    - name: Move pdf to artifacts
      run: mkdir -p ${{ env.OUTPUT_DIR }} && mv ${{ env.FILE }}.pdf ${{ env.OUTPUT_DIR }}/${{ env.FILE }}.pdf
    - name: Upload pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.OUTPUT_DIR }}/${{ env.FILE }}.pdf
        path: ./${{ env.OUTPUT_DIR }}