env: 
  INPUT_NAME: codern-report
  OUTPUT_NAME: codern-latex

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.INPUT_NAME }}.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ env.OUTPUT_NAME }}.pdf